import { Router } from 'express';
import * as c from '../controllers/admin.controller.js';
import { authenticate } from '../middlewares/authenticate.js';
import { requireRole } from '../middlewares/requireRole.js';
import { validate } from '../middlewares/validate.js';
import { userUpdateSchema, settingsSchema, reviewSchema } from '../validators/index.js';
import { list as listProperties } from '../controllers/property.controller.js';
const router = Router();
router.use(authenticate, requireRole('ADMIN'));
router.get('/stats', c.stats);
router.get('/users', c.users);
router.patch('/users/:id', validate(userUpdateSchema), c.updateUser);
router.get('/properties', listProperties);
router.get('/settings', c.settings);
router.patch('/settings', validate(settingsSchema), c.updateSettings);
router.get('/kyc', c.kycQueue);
router.patch('/kyc/:userId', validate(reviewSchema), c.reviewKyc);
router.get('/withdrawals', c.withdrawals);
router.patch('/withdrawals/:id', validate(reviewSchema), c.reviewWithdrawal);
export default router;
